### ISSUE TITLE
(opinion alert) use arrow functions instead of `.bind`

### ISSUE THREAD

**Issue by qpwo** [miltoncandelero/pixi-elementals#13]
I think it's a bit less confusing for beginners.

```
class A {
    private myName: string = "I am A";
    public method: Function;
}

class B {
    private myName: string = "I am B";

    public printName = () => {
        // Here... what does "this" means?!
        console.log(this.myName);
    }
}

const a = new A();
const b = new B();

a.method = b.printName;
a.method(); // This will print "I am B"
b.printName(); // This will print "I am B"
```

**Comment by miltoncandelero** [comment]
Class methods are stored inside the prototype and only one reference is shared for all objects of the same class.

Arrow functions assigned to a property of a class are part of each particular instance.

That means that having many instances of a function that has an arrow function means many copies of that function.

You can argue that modern devices have enough ram to disregard this but I like being kinda tidy 😅

You can test what I say about multiple copies of the same function with this simple script:

```ts
class A {
    public func(): void {
        console.log("function")
    }

    public arrow: () => void = () => {
        console.log("arrow")
    }
}

const foo:A = new A();
const bar:A = new A();

console.log(foo.func == bar.func);
console.log(foo.arrow == bar.arrow);
```

**Comment by qpwo** [comment]
TIL thank you. Changed my mind
