### ISSUE TITLE
AnimatedSprite expects array of TextureSource not String

### ISSUE THREAD

**Issue by buttery-x3** [miltoncandelero/pixi-elementals#55]
**Bug Description**
In the AnimatedSprite section following the code results in the following error:

>TS2345: Argument of type 'String' is not assignable to parameter of type 'TextureSource | TextureSource[]'.
>Type 'String' is missing the following properties from type 'TextureSource[]': pop, push, join, reverse, and 21 more.

After importing the TextureSource class and making the array of type TextureSource instead of String it compiled as expected.

**Comment by miltoncandelero** [comment]
`String` is not `string`

`number`, `string`, `boolean` and `object` are the javascript primitives
`Number`, `String`, `Boolean` and `Object` are object version of the primitives.

As a general rule, always use the lowercase ones except when calling static functions like `Object.keys(...)` or `Number.IsNaN(...)`

---

Side note, TextureSource is `export type TextureSource = string | BaseTexture | ImageSource;` so `string` (lowercase) is a `TextureSource`
